const os = require('node:os')
const fs = require('node:fs')
const path = require('node:path')

console.log('Starting...')
console.log('OS:', os.platform())
console.log('OS Version:', os.release())
console.log('OS Architecture:', os.arch())
console.log('OS Memory:', os.totalmem() / 1024 / 1024)
console.log('OS Free Memory:', os.freemem() / 1024 / 1024)
console.log('OS Uptime:', os.uptime())
console.log('OS Hostname:', os.hostname())
