### Invoke 404 Not Found
GET http://localhost:3000/

### Shows the same Body content as the previous request
POST http://localhost:3000/pokemon
Content-Type: application/json

{
  "name": "Ditto",
  "type": "Normal",
  "level": 10
}

### Invoke abiliity to retrieve a list of Pokémon
GET http://localhost:3000/pokemon/ditto

### Send the total update
PUT http://localhost:3000/update

### Not mapped http verb - 405 Method Not Allowed
OPTIONS http://localhost:3000/