### Invoke Hello World!
GET http://localhost:3000/test

### Invoke error
GET http://localhost:3000/test/error

### Invoke abiliity to retrieve a list of Pokémon
GET http://localhost:3000/test/pokemon/ditto

### Shows the same Body content as the previous request
POST http://localhost:3000/test/pokemon
Content-Type: application/json

{
  "name": "Ditto",
  "type": "Normal",
  "level": 10
}

###
GET http://localhost:3000/v1/logger

###  404 Not Found!!!!
PUT http://localhost:3000/update
